name: Execução por webhook
on:
  repository_dispatch:
    types: [chamada_executada]
jobs:
  first-action:
    runs-on: ubuntu-latest
    steps:
      - name: Exibindo mensagem
        run: echo "Workflow disparado por webhook"
      - name: Verificando TOKEN
        run: curl -X POST -d {“teste”:235, "token":${{ secrets.GITHUB_TOKEN}}}   