name: Estudando chamada de outro worker process
on:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: teste 01
        run: echo "Escrevendo a primeira linha"
  CD:
    needs: [CI]
    uses: https://github.dev/EduardoPrudencio/github-actions/.github/workflows/cd.yaml@main

          