name: Segundo dia de estudo
run-name: Executado por ${{ github.actor }}
on:
  workflow_dispatch:
jobs:
 first:
    runs-on: ubuntu-latest
    steps:
      - name: Executando a primeira linha
        run: echo "Escrevendo a promeira linha"    