name: Teste V de chamada de workflow
on:
  workflow_dispatch
jobs:
  CI:
    runs-on: ubuntu-laste
    steps:
      - name: Execução da primeira linha
        run: Primeira lina sendo executada  
  CD:
    needs: [CI]
    uses: EduardoPrudencio/github-actions/.github/workflows/cd.yaml@main      