name: Exemplos de estudos de inputs, outputs e artifacts
run-name: Exemplo de workflow executado por ${{ github.actor }}
on:
   workflow_dispatch:
        inputs:
            versao:
              type: string
              required: true
              default: "dev"
              description: "Versão da nova release"
            numero_card:
              type: number
              required: true
              description: "Número do card da tarefa relacionada ao commit"
            executar_deploy:
              type: boolean
              required: true
              default: false
              description: "Especifica se deve ou não realizar deploy"
            ambiente:
              type: choice
              required: true
              description: "Definição do ambiente onde o deploy será realizado"
              options:
                - Desenvolvimento
                - Homologação
                - Produção

env:
   nome-artefato: teste-artefato                
jobs:
  valores_input:
    runs-on: ubuntu-latest
    steps:
      - name: Exibindo dados dos inputs
        run: echo "${{ toJson(inputs)}}" 
      - name: Exibindo os valores individualmente
        run: |
          echo "Esses são os valores informados"
          echo "Versão: ${{ inputs.versao}}"
          echo "O card é: ${{ inputs.numero_card}}"    
          echo "Deve realizar deploy: ${{ inputs.executar_deploy}}"    
          echo "Ambiente de deploy: ${{ inputs.ambiente }}"
      - name: Gerando output com shell
        id: exemplo-output
        run: | 
          ACTION_RANDOM=$(( RANDOM ))
          echo "action_random=$ACTION_RANDOM" >> $GITHUB_OUTPUT

      - name: Exibindo o resultado da action exemplo-output
        run: echo "${{ steps.exemplo-output.outputs.action_random }}"

  criando-upload-de-artifact:
    runs-on: ubuntu-latest
    needs: [valores_input]
    steps:
      - name: Exibindo arquivos
        run: ls
      - name: Criando arquivos com dados dos inputs
        run: |
            mkdir artefatos
            echo "Versão: ${{ inputs.versao}}" > ./artefatos/deploy.txt
            echo "Número do card: ${{ inputs.numero_card}}" >> ./artefatos/deploy.txt
            echo "Deve realizar deploy: ${{ inputs.executar_deploy}}" >> ./artefatos/deploy.txt
            echo "Ambiente de deploy: ${{ inputs.ambiente}}" >> ./artefatos/deploy.txt
      - name: Enviando arquivos para o Github Artifact
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
           name: ${{ env.nome-artefato }}
           path: ./artefatos
      
      - name: Endereço para obtenção dos arquivos
        run: |
           echo "${{ steps.upload-artifact.outputs.artifact-url }}"
           
  download-artifact:
    runs-on: ubuntu-latest
    needs: [criando-upload-de-artifact]
    steps:
      - name: Listando arquivos
        run: ls

      - name: Baixando artefato
        uses: actions/download-artifact@v4
        with:
           name: ${{ env.nome-artefato }}
