name: Segundo dia de estudo
run-name: Executado por ${{ github.actor }}
on:
  workflow_dispatch:
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Exemplo de execução
        run: echo "Executando a primeira linha"