name: Quarto dia de estudo
run-name: Executado por ${{ github.actor}}
on:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Primeira linha
        run: echo "Vai rodar apenas em main."
      - name: Verificação
        if: ${{github.ref == 'refs/heads/main'}}
        run: echo "Está rodanod na main!"  
    