name: workflow de CI
on:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Simulando a primeira linha
        run: echo "Executando a primeira linha do primeiro workflow"
  CD:
    needs: [CI]
    uses: EduardoPrudencio/github-actions/.github/workflows/cd.yaml@main