name: workflow de CI
on:
  workflow_dispatch:
jobs:
  CI:
    environment: producao
    runs-on: ubuntu-latest
    steps:
      - name: Simulando a primeira linha
        run: echo "Executando a primeira linha do primeiro workflow"
      - name: Pegando valor de variável por ambinete
        run: echo "Aqui o valor é ${{ vars.VALOR}}"
  CD:
    needs: [CI]
    uses: EduardoPrudencio/github-actions/.github/workflows/cd.yaml@main
    with:
      valor_um: Texto para valor um
    secrets:
      version: ${{secrets.VERSION_VALUE}}  
      #VALOR