name: Teste de chamada de workflow
run-name: Teste executado por ${{ github.actor }} 
on:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Primeira linha
        run: echo "Executanod a primeira linha"
  CD:
    needs: [CI]
    uses: EduardoPrudencio/github-actions/.github/workflows/cd.yaml@main
  