name: Exibindo o nome da branch
run-name: Executado por ${{ github.actor }}
on:
  workflow_dispatch:
jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - name: Executar tarefa apenas na main
          if: ${{ github.ref == 'refs/heads/main' }}
          run: echo "Rodando na branch main"

