name: Exibindo o nome da branch
run-name: Executado por ${{ github.actor }}
on:
  workflow_dispatch:
jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - name: Exibindo o nome
          run: echo "${{github.ref}}"  
