name: Workflow criado para exemplo de reaproveitamento de workflow
on:
  workflow_call:
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Comando do workflow chamado
        run: echo "Executando o comando do worflow chamado"  