name: Workflow criado para exemplo de reaproveitamento de workflow
on:
  workflow_call:
    inputs:
      valor_um:
        type: string
        required: true
    secrets:
      version:
        required: true
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Exibindo o valor recebido por input
        run: echo "O valor informado foi ${{inputs.valor_um}}"
      - name: Comando do workflow chamado
        run: echo "Executando o comando do worflow chamado da versão ${{ secrets.version}}"
      - name: Envio de parâmetro por webhook
        run: "curl -X POST https://webhook.site/67072ee0-3198-421a-96b8-64681ec8cefc -d '{ambiente: ${{secrets.version}}}'"